passflow:
  path_to_class: models.passflow.passflow
  class_name: PassFlow
  path_to_config: ./models/passflow/CONF/config.yaml

  test_args:
    gs: True

plrgan:
  path_to_class: models.plr.PasswordGAN.PLRGAN
  class_name: PLRGAN
  path_to_config: ./models/plr/PasswordGAN/CONF/config.yaml

  test_args:
    ds: True

passgan:
  path_to_class: models.PassGAN.PassGAN
  class_name: PassGAN
  path_to_config: ./models/PassGAN/CONF/config.yaml

passgpt:
  path_to_class: models.PassGPT.PassGPT
  class_name: PassGPT
  path_to_config: ./models/PassGPT/CONF/config.yaml

vgpt2:
  path_to_class: models.VGPT2.VGPT2
  class_name: VGPT2
  path_to_config: ./models/VGPT2/CONF/config.yaml

fla:
  path_to_class: models.FLA.FLA
  class_name: FLA
  path_to_config: ./models/FLA/CONF/config.yaml